os: "linux"
arch: "amd64"

kube_vip_version: "v0.8.3"
vip_interface: ens18 
vip: 192.168.1.210 # This is the common floating IP address for the cluster

metallb_version: "v0.14.8"
lb_range: 192.168.1.240-192.168.1.249
lb_pool_name: first-pool

rke2_version: "v1.31.0+rke2r1"
rke2_install_dir: "/usr/local/bin"
rke2_binary_url: "https://github.com/rancher/rke2/releases/download/{{ rke2_version }}/rke2.linux-amd64"

ansible_user: gmirsky
ansible_become: true
ansible_become_method: sudo 
