---
- name: "Copy the kube config file"
  hosts: server1
  tasks:
    - name: "Copy the file"
      ansible.builtin.copy:
        src: ".kube/config"
        dest: ".kube/kube.txt"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: u+r,g-rw,o-rw
        remote_src: true
    - name: "Change the vip address"
      ansible.builtin.replace:
        path: ".kube/kube.txt"
        regexp: 'server: https:\/\/\d{1,3}.\d{1,3}.\d{1,3}.\d{1,3}:6443'
        replace: 'server: https://{{ vip }}:6443'
    - name: "Fetch the VIP config file"
      ansible.builtin.fetch:
        src: ".kube/kube.txt"
        dest: "kube.txt"
        flat: true
        fail_on_missing: true
